### ISSUE TITLE
Invalid query for NumericField(Key=True) on some values

### ISSUE THREAD

**Issue by azhmur** [chriseldredge/Lucene.Net.Linq#6]
Trying delete/insert for key value 5501, i got exception in QueryParser:

Lucene.Net.QueryParsers.ParseException occurred
  HResult=-2146233088
  Message=Cannot parse '`   *}': Lexical error at line 1, column 7.  Encountered: <EOF> after : ""
  Source=Lucene.Net
  StackTrace:
       at Lucene.Net.QueryParsers.QueryParser.Parse(String query) in d:\Lucene.Net\FullRepo\trunk\src\core\QueryParser\QueryParser.cs:line 239
  InnerException: Lucene.Net.QueryParsers.TokenMgrError
       HResult=-2146232832
       Message=Lexical error at line 1, column 7.  Encountered: <EOF> after : ""
       Source=Lucene.Net
       StackTrace:
            at Lucene.Net.QueryParsers.QueryParserTokenManager.GetNextToken() in d:\Lucene.Net\FullRepo\trunk\src\core\QueryParser\QueryParserTokenManager.cs:line 1429
            at Lucene.Net.QueryParsers.QueryParser.Jj_ntk() in d:\Lucene.Net\FullRepo\trunk\src\core\QueryParser\QueryParser.cs:line 1929
            at Lucene.Net.QueryParsers.QueryParser.Term(String field) in d:\Lucene.Net\FullRepo\trunk\src\core\QueryParser\QueryParser.cs:line 1461
            at Lucene.Net.QueryParsers.QueryParser.Clause(String field) in d:\Lucene.Net\FullRepo\trunk\src\core\QueryParser\QueryParser.cs:line 1383
            at Lucene.Net.QueryParsers.QueryParser.Query(String field) in d:\Lucene.Net\FullRepo\trunk\src\core\QueryParser\QueryParser.cs:line 1301
            at Lucene.Net.QueryParsers.QueryParser.TopLevelQuery(String field) in d:\Lucene.Net\FullRepo\trunk\src\core\QueryParser\QueryParser.cs:line 1287
            at Lucene.Net.QueryParsers.QueryParser.Parse(String query) in d:\Lucene.Net\FullRepo\trunk\src\core\QueryParser\QueryParser.cs:line 223
       InnerException:

**Comment by chriseldredge** [comment]
I've identified why this is happening but need to investigate how to fix it.
